### ISSUE TITLE
Unable to install from pip using Python 3 due to missing sdist or py3 wheel

### ISSUE THREAD

**Issue by drewsilcock** [freelawproject/seal-rookery#17]
When I try to install this package from PyPI using pip with Python 3, pip is only able to find versions `0.9.20` and `0.9.24` (which are not the most recent versions of the package, nor are they compatible with Python 3).

If you look at the full data for the package (see: https://pypi.org/pypi/seal_rookery/json) you can see all the different distributions that have been downloaded for each release.

If you look at `0.9.20` and `0.9.24` you can see that they both have an `sdist` release (i.e. source distribution) while the others only have `bdist_wheel` (a binary format) releases which are Python 2 only (because they were created with Python 2). As such, it looks like in order to allow Python 3 users to install the package from pip, you need to either:

- upload an `sdist` as well as a bdist_wheel for each release (official recommendation is to always upload an `sdist` as it's used by pip as a fallback)
- upload a `bdist_wheel` for Python 3 as well as Python 2 for each release
- both of the above (recommended)

This should be simple to do with twine, the docs here have detailed step-by-step instructions: https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives.

**Comment by drewsilcock** [comment]
p.s. there's a nice GitHub action for doing this now, all you need to do is tag the version and GitHub actions will upload it to PyPI for you. Info:

- https://github.com/marketplace/actions/pypi-publish
- https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by mlissner** [comment]
You have excellent timing, @drewsilcock. @flooie was working on this very issue yesterday. I'll let him take it from here.

**Comment by flooie** [comment]
Thanks @drewsilcock - this is great to know

**Comment by mlissner** [comment]
Just needs release automation and a tagged commit to release it.

**Comment by flooie** [comment]
@drewsilcock @mlissner tagged and released as v0.10.0

**Comment by mlissner** [comment]
Woo!
