### ISSUE TITLE
Convert seal pics into a cloud-first repository and service

### ISSUE THREAD

**Issue by mlissner** [freelawproject/seal-rookery#22]
In https://github.com/freelawproject/judge-pics/issues/15, I lay out the path to upgrade judge-pics to version 2.0 and in https://github.com/freelawproject/courtlistener/issues/1943, I discuss the need to remove seal-rookery from CourtListener. 

Although we're not going to use seal rookery much anymore, I believe it should be easy to give it the same treatment as the judge-pics so that we're consistent in our offerings. The only extra bits to consider are:

1. We need a domain for the seals. Let's go with rookery.free.law.

I think that's it. :)

We just need to bring the seals along for the ride. If this becomes a complicated thing, we can just say sorry, and abandon seals, but I'd prefer not to just because we don't usually roll that way.

**Comment by flooie** [comment]
I think this is/was completed.

**Comment by mlissner** [comment]
Hell yeah it is!
