### ISSUE TITLE
update-seals doesn't work on new installation

### ISSUE THREAD

**Issue by mlissner** [freelawproject/seal-rookery#7]
The idea here is that we run `update-seals` whenever we pull new seals and when we first install the package.

But `update-seals` makes a decision for each seal: "Is the hash on disk the same as the one in the JSON?" If so, it does nothing. If not, it updates the seal. 

We need to tweak this to either:

 - Have a new parameter that forces all seals to be updated, which we can run on first installation, or
 - Have it check if the seal exists at various sizes in addition to checking the hash.

I think I'm partial to the former. It seems simpler.

**Comment by voutilad** [comment]
I just noticed this as well. I like the idea of a forced regen. I'll see if I can fix this as I want to add a validation step for the FreeLawMachine after running update-seals.

**Comment by voutilad** [comment]
Btw, I'm actively working this in the `issue-7` branch.

**Comment by voutilad** [comment]
I think this is resolved, right?

**Comment by mlissner** [comment]
I'd say so, yeah. Closing.
