### ISSUE TITLE
update-seals returns non-zero exit code

### ISSUE THREAD

**Issue by voutilad** [freelawproject/seal-rookery#9]
Running the `update-seals` command that `setup.py` is installing returns a non-zero exit status to the shell (looks like a value of `1`) which causes tools like Ansible to think the command execution resulted in failure.

Looks like it's based on how I originally implemented the call to the method. Needs a minor refactor.

**Comment by mlissner** [comment]
I had a feverish and horrible upgrade over the weekend during which time I fixed this and pushed out a new release to pip. I forgot to push the code back here though. Fixed.
